export const countries: Record<string, string[]> = {
  KR: ["서울", "부산", "대구"],
  US: ["뉴욕", "로스앤젤레스", "보스턴", "시카고", "샌프란시스코"],
  CA: ["토론토", "밴쿠버", "몬트리올"],
  UK: ["런던", "맨체스터", "에든버러"],
  AU: ["시드니", "멜버른", "브리즈번"],
  DE: ["베를린", "뮌헨", "프랑크푸르트", "함부르크"],
  FR: ["파리", "리옹", "마르세유"],
  JP: ["도쿄", "오사카", "교토"],
  CN: ["베이징", "상하이", "광저우"],
  SG: ["싱가포르"],
  SE: ["스톡홀름", "고텐버그"],
  NL: ["암스테르담", "로테르담"],
  ES: ["바르셀로나", "마드리드", "세비야"],
  IT: ["로마", "밀라노", "피렌체"],
};

export const countryCodes: Record<string, string> = {
  대한민국: "KR",
  미국: "US",
  캐나다: "CA",
  영국: "UK",
  호주: "AU",
  독일: "DE",
  프랑스: "FR",
  일본: "JP",
  중국: "CN",
  싱가포르: "SG",
  스웨덴: "SE",
  네덜란드: "NL",
  스페인: "ES",
  이탈리아: "IT",
};

export const regionCode: Record<string, string> = {
  서울: "SEOUL",
  부산: "BUSAN",
  대구: "DAEGU",
  뉴욕: "NEWYORK",
  로스앤젤레스: "LOSANGELES",
  보스턴: "BOSTON",
  시카고: "CHICAGO",
  샌프란시스코: "SANFRANCISCO",
  토론토: "TORONTO",
  밴쿠버: "VANCOUVER",
  몬트리올: "MONTREAL",
  런던: "LONDON",
  맨체스터: "MANCHESTER",
  에든버러: "EDINBURGH",
  시드니: "SYDNEY",
  멜버른: "MELBOURNE",
  브리즈번: "BRISBANE",
  베를린: "BERLIN",
  뮌헨: "MUNICH",
  프랑크푸르트: "FRANKFURT",
  함부르크: "HAMBURG",
  파리: "PARIS",
  리옹: "LYON",
  마르세유: "MARSEILLE",
  도쿄: "TOKYO",
  오사카: "OSAKA",
  교토: "KYOTO",
  베이징: "BEIJING",
  상하이: "SHANGHAI",
  광저우: "GUANGZHOU",
  싱가포르: "SINGAPORE",
  스톡홀름: "STOCKHOLM",
  고텐버그: "GOTHENBURG",
  암스테르담: "AMSTERDAM",
  로테르담: "ROTTERDAM",
  바르셀로나: "BARCELONA",
  마드리드: "MADRID",
  세비야: "SEVILLE",
  로마: "ROME",
  밀라노: "MILAN",
  피렌체: "FLORENCE",
};

export const majorCode: Record<string, string> = {
  경영학과 : "BUSINESSADMINISTRATION",
  경제학과 : "ECONOMICS",  
}
