module.exports = {
  school: [
    {
      id: 1,
      schoolName: "서울대학교",
      country: "KR",
      region: "SEOUL",
      students: 27000,
    },
    {
      id: 2,
      schoolName: "부산대학교",
      country: "KR",
      region: "BUSAN",
      students: 15000,
    },
    {
      id: 3,
      schoolName: "하버드 대학교",
      country: "US",
      region: "BOSTON",
      students: 21000,
    },
    {
      id: 4,
      schoolName: "캘리포니아 대학교 로스앤젤레스",
      country: "US",
      region: "LOSANGELES",
      students: 31000,
    },
    {
      id: 5,
      schoolName: "시카고 대학교",
      country: "US",
      region: "CHICAGO",
      students: 26000,
    },
    {
      id: 6,
      schoolName: "뉴욕 대학교",
      country: "US",
      region: "NEWYORK",
      students: 24000,
    },
    {
      id: 7,
      schoolName: "토론토 대학교",
      country: "CA",
      region: "TORONTO",
      students: 28000,
    },
    {
      id: 8,
      schoolName: "브리티시 컬럼비아 대학교",
      country: "CA",
      region: "VANCOUVER",
      students: 24000,
    },
    {
      id: 9,
      schoolName: "맥길 대학교",
      country: "CA",
      region: "MONTREAL",
      students: 20000,
    },
    {
      id: 10,
      schoolName: "옥스퍼드 대학교",
      country: "UK",
      region: "LONDON",
      students: 22000,
    },
    {
      id: 11,
      schoolName: "맨체스터 대학교",
      country: "UK",
      region: "MANCHESTER",
      students: 18000,
    },
    {
      id: 12,
      schoolName: "에든버러 대학교",
      country: "UK",
      region: "EDINBURGH",
      students: 15000,
    },
    {
      id: 13,
      schoolName: "멜버른 대학교",
      country: "AU",
      region: "MELBOURNE",
      students: 32000,
    },
    {
      id: 14,
      schoolName: "시드니 대학교",
      country: "AU",
      region: "SYDNEY",
      students: 29000,
    },
    {
      id: 15,
      schoolName: "퀸즐랜드 대학교",
      country: "AU",
      region: "BRISBANE",
      students: 27000,
    },
    {
      id: 16,
      schoolName: "베를린 훔볼트 대학교",
      country: "DE",
      region: "BERLIN",
      students: 18000,
    },
    {
      id: 17,
      schoolName: "뮌헨 공과대학교",
      country: "DE",
      region: "MUNICH",
      students: 21000,
    },
    {
      id: 18,
      schoolName: "프랑크푸르트 대학교",
      country: "DE",
      region: "FRANKFURT",
      students: 16000,
    },
    {
      id: 19,
      schoolName: "함부르크 대학교",
      country: "DE",
      region: "HAMBURG",
      students: 14000,
    },
    {
      id: 20,
      schoolName: "파리 소르본 대학교",
      country: "FR",
      region: "PARIS",
      students: 26000,
    },
    {
      id: 21,
      schoolName: "리옹 대학교",
      country: "FR",
      region: "LYON",
      students: 12000,
    },
    {
      id: 22,
      schoolName: "엑스 마르세유 대학교",
      country: "FR",
      region: "MARSEILLE",
      students: 15000,
    },
    {
      id: 23,
      schoolName: "도쿄 대학교",
      country: "JP",
      region: "TOKYO",
      students: 35000,
    },
    {
      id: 24,
      schoolName: "오사카 대학교",
      country: "JP",
      region: "OSAKA",
      students: 18000,
    },
    {
      id: 25,
      schoolName: "교토 대학교",
      country: "JP",
      region: "KYOTO",
      students: 21000,
    },
    {
      id: 26,
      schoolName: "북경 대학교",
      country: "CN",
      region: "BEIJING",
      students: 33000,
    },
    {
      id: 27,
      schoolName: "상하이 푸단 대학교",
      country: "CN",
      region: "SHANGHAI",
      students: 28000,
    },
    {
      id: 28,
      schoolName: "중산 대학교",
      country: "CN",
      region: "GUANGZHOU",
      students: 25000,
    },
    {
      id: 29,
      schoolName: "싱가포르 국립대학교",
      country: "SG",
      region: "SINGAPORE",
      students: 25000,
    },
    {
      id: 30,
      schoolName: "스톡홀름 대학교",
      country: "SE",
      region: "STOCKHOLM",
      students: 12000,
    },
    {
      id: 31,
      schoolName: "고텐버그 대학교",
      country: "SE",
      region: "GOTHENBURG",
      students: 10000,
    },
    {
      id: 32,
      schoolName: "암스테르담 대학교",
      country: "NL",
      region: "AMSTERDAM",
      students: 21000,
    },
    {
      id: 33,
      schoolName: "로테르담 대학교",
      country: "NL",
      region: "ROTTERDAM",
      students: 15000,
    },
    {
      id: 34,
      schoolName: "바르셀로나 대학교",
      country: "ES",
      region: "BARCELONA",
      students: 23000,
    },
    {
      id: 35,
      schoolName: "마드리드 콤플루텐세 대학교",
      country: "ES",
      region: "MADRID",
      students: 25000,
    },
    {
      id: 36,
      schoolName: "세비야 대학교",
      country: "ES",
      region: "SEVILLE",
      students: 16000,
    },
    {
      id: 37,
      schoolName: "로마 사피엔자 대학교",
      country: "IT",
      region: "ROME",
      students: 27000,
    },
    {
      id: 38,
      schoolName: "밀라노 대학교",
      country: "IT",
      region: "MILAN",
      students: 21000,
    },
    {
      id: 39,
      schoolName: "피렌체 대학교",
      country: "IT",
      region: "FLORENCE",
      students: 14000,
    },
    {
      id: 40,
      schoolName: "스탠퍼드 대학교",
      country: "US",
      region: "SANFRANCISCO",
      students: 17000,
    },
    {
      id: 41,
      schoolName: "예일 대학교",
      country: "US",
      region: "NEWYORK",
      students: 19000,
    },
    {
      id: 42,
      schoolName: "프린스턴 대학교",
      country: "US",
      region: "NEWYORK",
      students: 8000,
    },
    {
      id: 43,
      schoolName: "콜롬비아 대학교",
      country: "US",
      region: "NEWYORK",
      students: 25000,
    },
    {
      id: 44,
      schoolName: "뉴사우스웨일스 대학교",
      country: "AU",
      region: "SYDNEY",
      students: 30000,
    },
    {
      id: 45,
      schoolName: "애들레이드 대학교",
      country: "AU",
      region: "MELBOURNE",
      students: 18000,
    },
    {
      id: 46,
      schoolName: "헬싱키 대학교",
      country: "FI",
      region: "HELSINKI",
      students: 20000,
    },
    {
      id: 47,
      schoolName: "빈 대학교",
      country: "AT",
      region: "VIENNA",
      students: 25000,
    },
    {
      id: 48,
      schoolName: "취리히 연방 공과대학교",
      country: "CH",
      region: "ZURICH",
      students: 12000,
    },
    {
      id: 49,
      schoolName: "로잔 공과대학교",
      country: "CH",
      region: "LAUSANNE",
      students: 11000,
    },
    {
      id: 50,
      schoolName: "이스탄불 대학교",
      country: "TR",
      region: "ISTANBUL",
      students: 31000,
    },
    {
      id: 51,
      schoolName: "두바이 대학교",
      country: "AE",
      region: "DUBAI",
      students: 14000,
    },
    {
      id: 52,
      schoolName: "도하 대학교",
      country: "QA",
      region: "DOHA",
      students: 8000,
    },
    {
      id: 53,
      schoolName: "남아공 대학교",
      country: "ZA",
      region: "JOHANNESBURG",
      students: 18000,
    },
    {
      id: 54,
      schoolName: "케이프타운 대학교",
      country: "ZA",
      region: "CAPE_TOWN",
      students: 16000,
    },
  ],
};
