module.exports = {
  schools: [
    {
      id: "SEOUL",
      name: "서울대학교",
      country: "KR",
      region: "SEOUL",
      students: 27000,
    },
    {
      id: "BUSAN",
      name: "부산대학교",
      country: "KR",
      region: "BUSAN",
      students: 15000,
    },
    {
      id: "HARVARD",
      name: "하버드 대학교",
      country: "US",
      region: "BOSTON",
      students: 21000,
    },
    {
      id: "UCLA",
      name: "캘리포니아 대학교 로스앤젤레스",
      country: "US",
      region: "LOSANGELES",
      students: 31000,
    },
    {
      id: "CHICAGO",
      name: "시카고 대학교",
      country: "US",
      region: "CHICAGO",
      students: 26000,
    },
    {
      id: "NYU",
      name: "뉴욕 대학교",
      country: "US",
      region: "NEWYORK",
      students: 24000,
    },
    {
      id: "TORONTO",
      name: "토론토 대학교",
      country: "CA",
      region: "TORONTO",
      students: 28000,
    },
    {
      id: "UBC",
      name: "브리티시 컬럼비아 대학교",
      country: "CA",
      region: "VANCOUVER",
      students: 24000,
    },
    {
      id: "MCGILL",
      name: "맥길 대학교",
      country: "CA",
      region: "MONTREAL",
      students: 20000,
    },
    {
      id: "OXFORD",
      name: "옥스퍼드 대학교",
      country: "UK",
      region: "LONDON",
      students: 22000,
    },
    {
      id: "MANCHESTER",
      name: "맨체스터 대학교",
      country: "UK",
      region: "MANCHESTER",
      students: 18000,
    },
    {
      id: "EDINBURGH",
      name: "에든버러 대학교",
      country: "UK",
      region: "EDINBURGH",
      students: 15000,
    },
    {
      id: "MELBOURNE",
      name: "멜버른 대학교",
      country: "AU",
      region: "MELBOURNE",
      students: 32000,
    },
    {
      id: "SYDNEY",
      name: "시드니 대학교",
      country: "AU",
      region: "SYDNEY",
      students: 29000,
    },
    {
      id: "QUEENSLAND",
      name: "퀸즐랜드 대학교",
      country: "AU",
      region: "BRISBANE",
      students: 27000,
    },
    {
      id: "HUMBOLDT",
      name: "베를린 훔볼트 대학교",
      country: "DE",
      region: "BERLIN",
      students: 18000,
    },
    {
      id: "TUM",
      name: "뮌헨 공과대학교",
      country: "DE",
      region: "MUNICH",
      students: 21000,
    },
    {
      id: "FRANKFURT",
      name: "프랑크푸르트 대학교",
      country: "DE",
      region: "FRANKFURT",
      students: 16000,
    },
    {
      id: "HAMBURG",
      name: "함부르크 대학교",
      country: "DE",
      region: "HAMBURG",
      students: 14000,
    },
    {
      id: "SORBONNE",
      name: "파리 소르본 대학교",
      country: "FR",
      region: "PARIS",
      students: 26000,
    },
    {
      id: "LYON",
      name: "리옹 대학교",
      country: "FR",
      region: "LYON",
      students: 12000,
    },
    {
      id: "AMU",
      name: "엑스 마르세유 대학교",
      country: "FR",
      region: "MARSEILLE",
      students: 15000,
    },
    {
      id: "TOKYO",
      name: "도쿄 대학교",
      country: "JP",
      region: "TOKYO",
      students: 35000,
    },
    {
      id: "OSAKA",
      name: "오사카 대학교",
      country: "JP",
      region: "OSAKA",
      students: 18000,
    },
    {
      id: "KYOTO",
      name: "교토 대학교",
      country: "JP",
      region: "KYOTO",
      students: 21000,
    },
    {
      id: "PKU",
      name: "북경 대학교",
      country: "CN",
      region: "BEIJING",
      students: 33000,
    },
    {
      id: "FUDAN",
      name: "상하이 푸단 대학교",
      country: "CN",
      region: "SHANGHAI",
      students: 28000,
    },
    {
      id: "ZSU",
      name: "중산 대학교",
      country: "CN",
      region: "GUANGZHOU",
      students: 25000,
    },
    {
      id: "NUS",
      name: "싱가포르 국립대학교",
      country: "SG",
      region: "SINGAPORE",
      students: 25000,
    },
    {
      id: "STOCKHOLM",
      name: "스톡홀름 대학교",
      country: "SE",
      region: "STOCKHOLM",
      students: 12000,
    },
    {
      id: "GOTHENBURG",
      name: "고텐버그 대학교",
      country: "SE",
      region: "GOTHENBURG",
      students: 10000,
    },
    {
      id: "AMSTERDAM",
      name: "암스테르담 대학교",
      country: "NL",
      region: "AMSTERDAM",
      students: 21000,
    },
    {
      id: "ROTTERDAM",
      name: "로테르담 대학교",
      country: "NL",
      region: "ROTTERDAM",
      students: 15000,
    },
    {
      id: "BARCELONA",
      name: "바르셀로나 대학교",
      country: "ES",
      region: "BARCELONA",
      students: 23000,
    },
    {
      id: "COMPLUTENSE",
      name: "마드리드 콤플루텐세 대학교",
      country: "ES",
      region: "MADRID",
      students: 25000,
    },
    {
      id: "SEVILLE",
      name: "세비야 대학교",
      country: "ES",
      region: "SEVILLE",
      students: 16000,
    },
    {
      id: "SAPIENZA",
      name: "로마 사피엔자 대학교",
      country: "IT",
      region: "ROME",
      students: 27000,
    },
    {
      id: "MILAN",
      name: "밀라노 대학교",
      country: "IT",
      region: "MILAN",
      students: 21000,
    },
    {
      id: "FLORENCE",
      name: "피렌체 대학교",
      country: "IT",
      region: "FLORENCE",
      students: 14000,
    },
    {
      id: "STANFORD",
      name: "스탠퍼드 대학교",
      country: "US",
      region: "SANFRANCISCO",
      students: 17000,
    },
    {
      id: "YALE",
      name: "예일 대학교",
      country: "US",
      region: "NEWYORK",
      students: 19000,
    },
    {
      id: "PRINCETON",
      name: "프린스턴 대학교",
      country: "US",
      region: "NEWYORK",
      students: 8000,
    },
    {
      id: "COLUMBIA",
      name: "콜롬비아 대학교",
      country: "US",
      region: "NEWYORK",
      students: 25000,
    },
    {
      id: "UNSW",
      name: "뉴사우스웨일스 대학교",
      country: "AU",
      region: "SYDNEY",
      students: 30000,
    },
    {
      id: "ADELAIDE",
      name: "애들레이드 대학교",
      country: "AU",
      region: "MELBOURNE",
      students: 18000,
    },
    {
      id: "HELSINKI",
      name: "헬싱키 대학교",
      country: "FI",
      region: "HELSINKI",
      students: 20000,
    },
    {
      id: "VIENNA",
      name: "빈 대학교",
      country: "AT",
      region: "VIENNA",
      students: 25000,
    },
    {
      id: "ETH",
      name: "취리히 연방 공과대학교",
      country: "CH",
      region: "ZURICH",
      students: 12000,
    },
    {
      id: "EPFL",
      name: "로잔 공과대학교",
      country: "CH",
      region: "LAUSANNE",
      students: 11000,
    },
    {
      id: "ISTANBUL",
      name: "이스탄불 대학교",
      country: "TR",
      region: "ISTANBUL",
      students: 31000,
    },
    {
      id: "DUBAI",
      name: "두바이 대학교",
      country: "AE",
      region: "DUBAI",
      students: 14000,
    },
    {
      id: "DOHA",
      name: "도하 대학교",
      country: "QA",
      region: "DOHA",
      students: 8000,
    },
    {
      id: "UCT",
      name: "남아공 대학교",
      country: "ZA",
      region: "JOHANNESBURG",
      students: 18000,
    },
    {
      id: "CAPE_TOWN",
      name: "케이프타운 대학교",
      country: "ZA",
      region: "CAPE_TOWN",
      students: 16000,
    },
  ],
  dormitory: [
    {
      id: "DUBLIN_UNIV_DORMITORY_1",
      name: "더블린 대학교 1기숙사",
      img: "https://i.namu.wiki/i/r7_sqLuPBKzM0Hd-aSu6CLvZNYm5UyGEJqvGdFUvRVdhQkByjjQmOxgGHrk3v7Qqmgyi8gi28gmly-OJ9cg8fHvqAXdm-qcwhM1HJIvN4dYz9zLwdAQgn2QiGrtFdDPIi8Lo-wlZv1-uIkIgqPMI2Q.webp",
      country: "IE",
      region: "DUBLIN",
    },
    {
      id: "SEOUL_UNIV_DORMITORY_1",
      name: "서울대학교 기숙사 1",
      img: "https://i.namu.wiki/i/r7_sqLuPBKzM0Hd-aSu6CLvZNYm5UyGEJqvGdFUvRVdhQkByjjQmOxgGHrk3v7Qqmgyi8gi28gmly-OJ9cg8fHvqAXdm-qcwhM1HJIvN4dYz9zLwdAQgn2QiGrtFdDPIi8Lo-wlZv1-uIkIgqPMI2Q.webp",
      country: "KR",
      region: "SEOUL",
    },
    {
      id: "BUSAN_UNIV_DORMITORY_1",
      name: "부산대학교 기숙사 1",
      img: "https://i.namu.wiki/i/r7_sqLuPBKzM0Hd-aSu6CLvZNYm5UyGEJqvGdFUvRVdhQkByjjQmOxgGHrk3v7Qqmgyi8gi28gmly-OJ9cg8fHvqAXdm-qcwhM1HJIvN4dYz9zLwdAQgn2QiGrtFdDPIi8Lo-wlZv1-uIkIgqPMI2Q.webp",
      country: "KR",
      region: "BUSAN",
    },
    {
      id: "HARVARD_UNIV_DORMITORY_1",
      name: "하버드 대학교 기숙사 1",
      img: "https://i.namu.wiki/i/r7_sqLuPBKzM0Hd-aSu6CLvZNYm5UyGEJqvGdFUvRVdhQkByjjQmOxgGHrk3v7Qqmgyi8gi28gmly-OJ9cg8fHvqAXdm-qcwhM1HJIvN4dYz9zLwdAQgn2QiGrtFdDPIi8Lo-wlZv1-uIkIgqPMI2Q.webp",
      country: "US",
      region: "BOSTON",
    },
    {
      id: "UCLA_UNIV_DORMITORY_1",
      name: "캘리포니아 대학교 로스앤젤레스 기숙사 1",
      img: "https://i.namu.wiki/i/r7_sqLuPBKzM0Hd-aSu6CLvZNYm5UyGEJqvGdFUvRVdhQkByjjQmOxgGHrk3v7Qqmgyi8gi28gmly-OJ9cg8fHvqAXdm-qcwhM1HJIvN4dYz9zLwdAQgn2QiGrtFdDPIi8Lo-wlZv1-uIkIgqPMI2Q.webp",
      country: "US",
      region: "LOSANGELES",
    },
    {
      id: "CHICAGO_UNIV_DORMITORY_1",
      name: "시카고 대학교 기숙사 1",
      img: "https://i.namu.wiki/i/r7_sqLuPBKzM0Hd-aSu6CLvZNYm5UyGEJqvGdFUvRVdhQkByjjQmOxgGHrk3v7Qqmgyi8gi28gmly-OJ9cg8fHvqAXdm-qcwhM1HJIvN4dYz9zLwdAQgn2QiGrtFdDPIi8Lo-wlZv1-uIkIgqPMI2Q.webp",
      country: "US",
      region: "CHICAGO",
    },
    {
      id: "NYU_UNIV_DORMITORY_1",
      name: "뉴욕 대학교 기숙사 1",
      img: "https://i.namu.wiki/i/r7_sqLuPBKzM0Hd-aSu6CLvZNYm5UyGEJqvGdFUvRVdhQkByjjQmOxgGHrk3v7Qqmgyi8gi28gmly-OJ9cg8fHvqAXdm-qcwhM1HJIvN4dYz9zLwdAQgn2QiGrtFdDPIi8Lo-wlZv1-uIkIgqPMI2Q.webp",
      country: "US",
      region: "NEWYORK",
    },
    {
      id: "TORONTO_UNIV_DORMITORY_1",
      name: "토론토 대학교 기숙사 1",
      img: "https://i.namu.wiki/i/r7_sqLuPBKzM0Hd-aSu6CLvZNYm5UyGEJqvGdFUvRVdhQkByjjQmOxgGHrk3v7Qqmgyi8gi28gmly-OJ9cg8fHvqAXdm-qcwhM1HJIvN4dYz9zLwdAQgn2QiGrtFdDPIi8Lo-wlZv1-uIkIgqPMI2Q.webp",
      country: "CA",
      region: "TORONTO",
    },
    {
      id: "UBC_UNIV_DORMITORY_1",
      name: "브리티시 컬럼비아 대학교 기숙사 1",
      img: "https://i.namu.wiki/i/r7_sqLuPBKzM0Hd-aSu6CLvZNYm5UyGEJqvGdFUvRVdhQkByjjQmOxgGHrk3v7Qqmgyi8gi28gmly-OJ9cg8fHvqAXdm-qcwhM1HJIvN4dYz9zLwdAQgn2QiGrtFdDPIi8Lo-wlZv1-uIkIgqPMI2Q.webp",
      country: "CA",
      region: "VANCOUVER",
    },
    {
      id: "MCGILL_UNIV_DORMITORY_1",
      name: "맥길 대학교 기숙사 1",
      img: "https://i.namu.wiki/i/r7_sqLuPBKzM0Hd-aSu6CLvZNYm5UyGEJqvGdFUvRVdhQkByjjQmOxgGHrk3v7Qqmgyi8gi28gmly-OJ9cg8fHvqAXdm-qcwhM1HJIvN4dYz9zLwdAQgn2QiGrtFdDPIi8Lo-wlZv1-uIkIgqPMI2Q.webp",
      country: "CA",
      region: "MONTREAL",
    },
    {
      id: "OXFORD_UNIV_DORMITORY_1",
      name: "옥스퍼드 대학교 기숙사 1",
      img: "https://i.namu.wiki/i/r7_sqLuPBKzM0Hd-aSu6CLvZNYm5UyGEJqvGdFUvRVdhQkByjjQmOxgGHrk3v7Qqmgyi8gi28gmly-OJ9cg8fHvqAXdm-qcwhM1HJIvN4dYz9zLwdAQgn2QiGrtFdDPIi8Lo-wlZv1-uIkIgqPMI2Q.webp",
      country: "UK",
      region: "LONDON",
    },
    {
      id: "CAMBRIDGE_UNIV_DORMITORY_1",
      name: "케임브리지 대학교 기숙사 1",
      img: "https://i.namu.wiki/i/r7_sqLuPBKzM0Hd-aSu6CLvZNYm5UyGEJqvGdFUvRVdhQkByjjQmOxgGHrk3v7Qqmgyi8gi28gmly-OJ9cg8fHvqAXdm-qcwhM1HJIvN4dYz9zLwdAQgn2QiGrtFdDPIi8Lo-wlZv1-uIkIgqPMI2Q.webp",
      country: "UK",
      region: "CAMBRIDGE",
    },
    {
      id: "STANFORD_UNIV_DORMITORY_1",
      name: "스탠포드 대학교 기숙사 1",
      img: "https://i.namu.wiki/i/r7_sqLuPBKzM0Hd-aSu6CLvZNYm5UyGEJqvGdFUvRVdhQkByjjQmOxgGHrk3v7Qqmgyi8gi28gmly-OJ9cg8fHvqAXdm-qcwhM1HJIvN4dYz9zLwdAQgn2QiGrtFdDPIi8Lo-wlZv1-uIkIgqPMI2Q.webp",
      country: "US",
      region: "PALOALTO",
    },
    {
      id: "MIT_UNIV_DORMITORY_1",
      name: "매사추세츠 공과대학교 기숙사 1",
      img: "https://i.namu.wiki/i/r7_sqLuPBKzM0Hd-aSu6CLvZNYm5UyGEJqvGdFUvRVdhQkByjjQmOxgGHrk3v7Qqmgyi8gi28gmly-OJ9cg8fHvqAXdm-qcwhM1HJIvN4dYz9zLwdAQgn2QiGrtFdDPIi8Lo-wlZv1-uIkIgqPMI2Q.webp",
      country: "US",
      region: "CAMBRIDGE",
    },
    {
      id: "YONSEI_UNIV_DORMITORY_1",
      name: "연세대학교 기숙사 1",
      img: "https://i.namu.wiki/i/r7_sqLuPBKzM0Hd-aSu6CLvZNYm5UyGEJqvGdFUvRVdhQkByjjQmOxgGHrk3v7Qqmgyi8gi28gmly-OJ9cg8fHvqAXdm-qcwhM1HJIvN4dYz9zLwdAQgn2QiGrtFdDPIi8Lo-wlZv1-uIkIgqPMI2Q.webp",
      country: "KR",
      region: "SEOUL",
    },
    {
      id: "KAIST_UNIV_DORMITORY_1",
      name: "KAIST 기숙사 1",
      img: "https://i.namu.wiki/i/r7_sqLuPBKzM0Hd-aSu6CLvZNYm5UyGEJqvGdFUvRVdhQkByjjQmOxgGHrk3v7Qqmgyi8gi28gmly-OJ9cg8fHvqAXdm-qcwhM1HJIvN4dYz9zLwdAQgn2QiGrtFdDPIi8Lo-wlZv1-uIkIgqPMI2Q.webp",
      country: "KR",
      region: "DAEJEON",
    },
  ],
};
